export {
  COPILOT_IDENTITY,
  BACKGROUND_CYCLE_PROMPT,
  MORNING_BRIEFING_PROMPT,
  CATCHUP_PROMPT,
  DECISION_SUPPORT_PROMPT,
  COMMUNICATION_DRAFT_PROMPT,
  PRE_MORTEM_PROMPT,
  STATUS_REPORT_PROMPT,
} from './system.js';
